---
- name: Test nvidia-smi command
  command: nvidia-smi
  register: nvidia_installed
  ignore_errors: yes
  changed_when: false

- name: Install drivers
  include_tasks: install.yml
  when: nvidia_installed is failed

